services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SERVICE_B_URL: http://data-api:8081/api/transform
      JWT_SECRET: your_very_long_and_very_secret_key_for_jwt_auth
      INTERNAL_TOKEN: dev_secret_123
    depends_on:
      - db

  data-api:
    build: ./data-api
    container_name: data-api
    ports:
      - "8081:8081"
    environment:
      INTERNAL_TOKEN: dev_secret_123